# NBA Franchise Analysis

The data for the franchise record was downloaded from https://www.kaggle.com/koki25ando/nba-franchise-record. Kaggle is a site for those that have an active interest in analytics and data science. One can choose any real-world datasets to work with. They can also participate in competitions hosted by Kaggle to take on real world challenges. People can choose to work in teams or alone. 

The data dictionary for the NBA Franchise record is provided below:

Franchise : Team Name

Lg : League name(s)

From : The year of establishment

To : The year of

Yrs : Franchise year

G : Games played

W : Wins

L : Losses

PCT : Winning percentage

Plyfs : the number of playoff appearance

Div : the number of division championship

Conf : the number of conference championship

Champ : The number of title

This analysis is in response to the following questions below:

1. Which team has the longest history?
2. Which team has the best winning percentage and worst winning percentage?

In [1]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Read in the csv file as dataframe
nba_franchise = pd.read_csv('NBA Franchise Record.csv')

In [5]:
# Check the data out
nba_franchise.info()

nba_franchise.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 14 columns):
Unnamed: 0    30 non-null int64
Franchise     30 non-null object
Lg            30 non-null object
From          30 non-null int64
To            30 non-null int64
Yrs           30 non-null int64
G             30 non-null int64
W             30 non-null int64
L             30 non-null int64
PCT           30 non-null float64
Plyfs         30 non-null int64
Div           30 non-null int64
Conf          30 non-null int64
Champ         30 non-null int64
dtypes: float64(1), int64(11), object(2)
memory usage: 3.4+ KB


Unnamed: 0    0
Franchise     0
Lg            0
From          0
To            0
Yrs           0
G             0
W             0
L             0
PCT           0
Plyfs         0
Div           0
Conf          0
Champ         0
dtype: int64

In [6]:
nba_franchise.head()

Unnamed: 0          Franchise       Lg  From    To  Yrs     G     W     L  \
0           1      Atlanta Hawks      NBA  1950  2018   69  5470  2717  2753   
1           2     Boston Celtics  NBA/BAA  1947  2018   72  5642  3329  2313   
2           3      Brooklyn Nets  NBA/ABA  1968  2018   51  4140  1782  2358   
3           4  Charlotte Hornets      NBA  1989  2018   28  2248   988  1260   
4           5      Chicago Bulls      NBA  1967  2018   52  4215  2183  2032   

     PCT  Plyfs  Div  Conf  Champ  
0  0.497     46   11     0      1  
1  0.590     55   31     9     17  
2  0.430     26    5     2      2  
3  0.440     10    0     0      0  
4  0.518     35    9     6      6

In [7]:
# Task 1: Find the franchise with the max amount of years in the league
nba_franchise['Yrs'].describe()

count    30.000000
mean     49.433333
std      16.604286
min      16.000000
25%      39.500000
50%      51.000000
75%      66.000000
max      72.000000
Name: Yrs, dtype: float64

Notice in the descriptive statistics that the maximum amount of years is 72. We want to create an object that sets the years variable greater than or equal to 72 and vice versa for the minimum amount of years.

In [8]:
# Creating new objects for maximum amount of years and minimum amount of years
long_nba_franchise = nba_franchise[nba_franchise['Yrs'] == 72]
short_nba_franchise = nba_franchise[nba_franchise['Yrs'] <= 16]

In [10]:
# Teams with the longest history in the NBA
long_nba_franchise

Unnamed: 0              Franchise       Lg  From    To  Yrs     G     W  \
1            2         Boston Celtics  NBA/BAA  1947  2018   72  5642  3329   
9           10  Golden State Warriors  NBA/BAA  1947  2018   72  5638  2715   
19          20        New York Knicks  NBA/BAA  1947  2018   72  5639  2761   

       L    PCT  Plyfs  Div  Conf  Champ  
1   2313  0.590     55   31     9     17  
9   2923  0.482     34   11     4      5  
19  2878  0.490     42    8     4      2

In [11]:
# Teams with the shortest history in the NBA
short_nba_franchise

Unnamed: 0             Franchise   Lg  From    To  Yrs     G    W    L  \
18          19  New Orleans Pelicans  NBA  2003  2018   16  1296  610  686   

      PCT  Plyfs  Div  Conf  Champ  
18  0.471      7    1     0      0

The teams with the longest history in the NBA are the Boston Celtics, Golden State Warrios, and the New York Knicks. As for the shortest history, it is the New Orleans Pelicans.

In [12]:
# Task 2: Find the teams that have the best winning percentage and the worst winning percentage
nba_franchise['PCT'].describe()

count    30.000000
mean      0.495433
std       0.052260
min       0.397000
25%       0.461750
50%       0.497500
75%       0.523750
max       0.602000
Name: PCT, dtype: float64

We apply the same approach for the percentage variable.

In [13]:
# Teams with the best winning percentage
top_nba_teams = nba_franchise[nba_franchise['PCT'] >= 0.602]

In [14]:
# Teams with the worst winning percentage
worst_nba_teams = nba_franchise[nba_franchise['PCT'] <= 0.397]

In [15]:
# View winning percentage
top_nba_teams

Unnamed: 0          Franchise       Lg  From    To  Yrs     G     W     L  \
26          27  San Antonio Spurs  NBA/ABA  1968  2018   51  4140  2492  1648   

      PCT  Plyfs  Div  Conf  Champ  
26  0.602     46   22     6      5

In [16]:
worst_nba_teams

Unnamed: 0               Franchise   Lg  From    To  Yrs     G    W     L  \
17          18  Minnesota Timberwolves  NBA  1990  2018   29  2330  925  1405   

      PCT  Plyfs  Div  Conf  Champ  
17  0.397      9    1     0      0

Here, we see that the San Antonio Spurs have the best winning percentage at 0.602 while the Minnesota Timberwolves are at 0.397. This is due to the fact that the San Antonio Spurs recorded more total wins than losses. They also had 46 playoff appearances and 6 finals appearances. Therefore, they were able to win 5 championships. Many factors include team culture, great coaching staff, and excellent offensive and defensive sets. However, leadership is the biggest key for the team to be the best they can be.